name: Create version bump PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version Number (x.x.x)'
        required: true
      is_prerelease:
        description: 'Is Prerelease version? (true/false)'
        default: 'false'
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      Version: "${{ github.event.inputs.version }}"
      IsPrerelease: "${{ github.event.inputs.is_prerelease }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Modify build-packages"
        id: "versions"
        run: |
          CURRENTVERSION="$(grep -o -e RELEASE_VERSION\=\"[0-9]*\.[0-9]*\.[0-9]*  dotnet/build-packages.sh | sed 's/RELEASE_VERSION="//')"
          echo Current version is: $CURRENTVERSION
          VERSION=${{ github.event.inputs.version }}
          echo new version is: $VERSION
          sed -i -e "s/$CURRENTVERSION/$VERSION/g" dotnet/build-packages.sh
          echo Replaced release version in file.
          echo "::set-output name=version::$VERSION"
          
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "version-bump-${{steps.versions.outputs.version}}"
          commit-message: "[Version Bump] ${{steps.versions.outputs.full_version}}"
          delete-branch: true
          title: "[.Net Version Bump] ${{steps.versions.outputs.version}}"
          body: "Dotnet Tracer Bump"

      - name: Display output
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"
